server:
  name: fintech
  port: 8081

mongo:
  url: mongodb://localhost
  port: 27017
  database: bnbprices

rabbitmq:
  url: amqp://guest:guest@localhost:5672/
  exchange_name: test
  exchange_kind: fanout
  queue_name: bnbprices

bnb:
  url: wss://stream.binance.com:9443/ws
#  listsymbol: ["cakeusdt","bnbusdt","btcusdt","ethusdt","xmrusdt","uniusdt","axsusdt","xlmusdt","ftmusdt","sushiusdt"]
  listsymbol: ["cakeusdt","bnbusdt","btcusdt","ethusdt","xmrusdt"]
#  listsymbol: ["cakeusdt","btcusdt"]
  kline: ["1m","5m","15m","30m","1h","2h","4h","1d","1w"]
#  kline: ["2h"]

filereader:
  path: "./inbound/signals.txt"